### ISSUE TITLE
[BUG]: Icons should not be focusable

### ISSUE THREAD

**Issue by michael** [shinokada/svelte-heros-v2#10]
### Description of the bug

I noticed that unlike in svelte-heros-v1 the icons receive a focus when tabbing through the focusable elements. I think this shouldn't happen.

### Steps To Reproduce

1. Use any Icon
2. Use TAB

**Comment by shinokada** [comment]
If you don't want a focusable icon add `tabindex="-1"`:

```html
<AcademicCap size="50" tabindex="-1" />
```

**Comment by joekrump** [comment]
@shinokada I'm curious what the thinking is behind having the icons be focusable by default vs opt in? In many cases I'm using the icon components within `<button>` elements which results in odd behaviour since a single tab focuses the button, then tabbing again focuses its inner icon.

**Comment by shinokada** [comment]
Svg icons are often used for components such as accordion, dropdown, etc. They require to be focusable since it opens/closes/toggles hidden components. 
If you don't want to them focusable, you can read "Setting Global Icon using setContext" and "Creating a Default Icon Setting" in the docs to create your custom icons.
